sudo: required
services:
  - docker

before_install:
  - docker pull node:8-onbuild

install:
  - docker build -t my-probot .

script:
  - docker run --rm my-probot npm run test
  - docker run --rm my-probot npm run lint

after_success:
  - docker tag my-probot my-probot:$(git rev-parse HEAD)
