sudo: required
services:
  - docker

#environment variables for matrix operation
env:
  - NPM_TARGET=test
  - NPM_TARGET=lint
  - NPM_TARGET=coverage

before_install:
  - docker pull node:8-onbuild

install:
  - docker build -t my-probot .

#runs at each instantiation of npm_target env var (test, lint and coverage run)
script:
  - docker run --rm my-probot npm run $NPM_TARGET

#only run on given condition
after_success:
  - set -x -v;
    set -e;
    if [ "${NPM_TARGET}" = "test" ]; then
      docker tag my-probot my-probot:$(git rev-parse HEAD);
    else
      echo "skipping docker tag";
    fi;
    docker images;
    set +x +v;
